// C# Translation of GoldParser, by Marcus Klimstra <klimstra@home.nl>.
// Based on GOLDParser by Devin Cook <http://www.devincook.com/goldparser>.

namespace Alachisoft.NosDB.Common.Queries.Parser
{
	/// This is a visitor-interface for the parse tree generated by GoldParser.
	/// See the sample project for more information.
	public interface IGoldVisitor
	{
		/// Visits the specified <c>Reduction</c>.
		void Visit(Reduction r);
	}
}
